fl_frontend:
  ros__parameters:
    use_sim_time: true
    odom_is_delta: true
    odom_topic: "/sim/odom"
    odom_frame: "odom_combined"
    base_frame: "base_footprint"
    use_3d_pointcloud: true
    enable_pointcloud: true
    pointcloud_topic: "/lidar/points"
    enable_image: false
    enable_depth: false
    enable_camera_info: false
    publish_rgbd_evidence: false
    camera_fx: 610.16
    camera_fy: 610.45
    camera_cx: 326.35
    camera_cy: 244.68
    lidar_base_extrinsic: [-0.011, 0.0, 0.778, 0.0, 0.0, 0.0]
    enable_imu: true
    imu_topic: "/livox/mid360/imu"
    imu_gyro_noise_density: 0.00017
    imu_accel_noise_density: 0.00019
    imu_accel_scale: 9.81
    keyframe_translation_threshold: 0.5
    keyframe_rotation_threshold: 0.26
    gravity: [0.0, 0.0, -9.81]

fl_backend:
  ros__parameters:
    use_sim_time: true
    odom_frame: "odom_combined"
    rgbd_evidence_topic: "/sim/rgbd_evidence"
    # NOTE: enable_imu_fusion removed - 15D state is always enabled
    gravity: [0.0, 0.0, -9.81]

livox_converter:
  ros__parameters:
    use_sim_time: true
    input_topic: "/livox/mid360/lidar"
    input_msg_type: "auto"
    output_topic: "/lidar/points"
    frame_id: "livox_frame"

image_decompress_cpp:
  ros__parameters:
    use_sim_time: true
    rgb_compressed_topic: "/camera/color/image_raw/compressed"
    depth_compressed_topic: "/camera/aligned_depth_to_color/image_raw/compressedDepth"
    rgb_output_topic: "/camera/image_raw"
    depth_output_topic: "/camera/depth/image_raw"
    depth_scale_mm_to_m: true
    qos_reliability: "reliable"

odom_bridge:
  ros__parameters:
    use_sim_time: true
    input_topic: "/odom"
    output_topic: "/sim/odom"
    output_frame: "odom_combined"
    child_frame: "base_footprint"
    qos_reliability: "reliable"
    validate_frames: false
